### ISSUE TITLE
Is there any way to target .NET Standard 1.4?

### ISSUE THREAD

**Issue by aloneguid** [gboucher90/thrift-netcore#1]
We are trying to create something in UWP with Thrift, however, unfortunately UWP platform supports .NET Standard up to 1.4 only which becomes a showstopper.

Do you know by any chance if this requirement can be lowered?

**Comment by gboucher90** [comment]
Hello,

Unfortunately the "BufferedStream" class is not available in NET Standard 1.4, the availability starts at 1.5:
https://docs.microsoft.com/en-us/dotnet/api/?view=netstandard-1.5&term=BufferedStream

We could make a degraded version, it wouldn't have TBufferedTransport and remove the support for buffered connection with TTLSServerSocket and TServerSocket. Would it still work for you?

**Comment by gboucher90** [comment]
I added a NetStandard 1.4 version without buffering support as mentioned above:
https://github.com/gboucher90/thrift-netcore/commit/951987fe6dd2785c38a4136bce618fe8b43e8c53

**Comment by aloneguid** [comment]
This is perfect, thanks so much. We are actually reading everything in memory, this is for the project https://github.com/elastacloud/parquet-dotnet

**Comment by gboucher90** [comment]
Cool project you have there!
If this is only for in memory I think we could go even lower if needed.
I updated the package on Nuget.org:
https://www.nuget.org/packages/apache-thrift-netcore/0.9.3.1
